### ISSUE TITLE
Enforce Consistent File Naming Conventions (use `.html` instead of `.htm`)

### ISSUE THREAD

**Issue by AnthonyByansi** [brianbuggah/KevinCookieCompany.com#3]
Hi @brianbuggah 
![Naming conventions](https://github.com/user-attachments/assets/6d5271ed-f186-4367-bcc1-f7bcc5429cee)

**Comment by brianbuggah** [comment]
Done

**Comment by AnthonyByansi** [comment]
All looking good, @brianbuggah 
You might want to consider https://github.com/brianbuggah/KevinCookieCompany.com/issues/8#issue-2742510308
